version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginxserver-ai
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
      - '4000:4000'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt